import Head from "next/head";
import React from "react";
import About from "../components/Pages/About";

const aboutus = () => {
	return (
		<>
			<Head>
				<title>AuthBrain || About Us</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<About />
			</div>
		</>
	);
};

export default aboutus;
