import Head from "next/head";
import React from "react";
import Contact from "../components/Pages/Connect/Contact";

const contact = () => {
	return (
		<>
			<Head>
				<title>AuthBrain || Contact</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Contact />
			</div>
		</>
	);
};

export default contact;
