import Head from "next/head";


import Banner2 from "../components/Homepage/Banner2";
import Faqs from "../components/Homepage/Faqs";
import WhoWeAre from "../components/Homepage/WhoWeAre";
import Whatweoffer from "../components/Homepage/Whatweoffer";
import StrategicServices from "../components/Homepage/StrategicServices";
import Implementation from "../components/Homepage/Implementation";
import Form from "../components/Homepage/Form";
import Blogs from "../components/Homepage/Blogs";

export default function Home() {
	return (
		<div >
			<Head>
				<title>SILLICOVALLEY || Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bg-[#F0F3F6]">
				<Banner2 />
				<WhoWeAre />
				<Whatweoffer />
				<StrategicServices />
				<Implementation />
				<Form />
				<Faqs />
				<Blogs />



			</div>
		</div>
	);
}
