import Head from "next/head";
import React from "react";
import Privacypolicy from "../components/Pages/Privacypolicy";

const privacypolicy = () => {
	return (
		<>
			<Head>
				<title>AuthBrain || Privacy Policy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Privacypolicy />
			</div>
		</>
	);
};

export default privacypolicy;
