import Head from "next/head";
import React from "react";
import Products from "../components/Pages/Products/Products";

const products = () => {
	return (
		<>
			<Head>
				<title>AuthBrain || Products </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Products />
			</div>
		</>
	);
};

export default products;
