import Head from "next/head";
import React from "react";
import Research from "../components/Pages/Research";

const research = () => {
	return (
		<>
			<Head>
				<title>AuthBrain || Research </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Research />
			</div>
		</>
	);
};

export default research;
