import Head from "next/head";
import React from "react";
import Solutions from "../components/Pages/Solutions/Solutions";

const solutions = () => {
	return (
		<>
			<Head>
				<title>AuthBrain || Solutions </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Solutions />
			</div>
		</>
	);
};

export default solutions;
